### PR TITLE
Add ja Translation

### PR DESCRIPTION
**Pull request by shg166**
Nice to meet you.
I was checking and found that it supports multiple languages.
It's too late now, but I've added the Japanese translation files.
If you can still update it, please do so.

### CODE REVIEW

**Comment by DaEgi01** [comment]
Hey, nice to meet you :)
Regarding japanese, I don't have that as a language option in the game.
image
I assume that you have it though.
Can you confirm that it works ingame for you?

**Review by DaEgi01 — APPROVED** [review]

**Comment by DaEgi01** [comment]
Also, there is a new version on the dev branch that does a few things differently.
Some items like "ItemHeight" do not exists anymore.
But we can postpone that until I'll release it.

**Comment by DaEgi01** [comment]
Put the version with japanese on the workshop.
Check it out :)

**Comment by shg166** [comment]
Thank you for merging them.
It was late at night, and I was asleep.

Thank you for the quick update.
Japanese is not present in the default language settings.
As you know, you can either use a mod or copy the Locale file directly to make it Japanese.
It is checked in-game before the pull request, so you should be fine.

I've also been able to check the workshop for updates, so no problem there.
If there is a plan for an update, the translation will be handled.

**Pull request merged**
